Repository Automattic/wpcom-proxy-request, pull requests merged in 2018-10, with the labels that each got.

#34 Fix vulnerabilites from npm audit
  package-lock.json
  package.json
Labels: [Status] Needs Review

#36 Patch File objects sent as form data to work around a bug in Chrome
  index.js
  package-lock.json
  package.json
Labels: [Status] Needs Review, bug

#37 Fix Chrome file upload workaround to avoid breaking Safari 10
  History.md
  index.js
  package-lock.json
  package.json
Labels: bug
